### PR TITLE
🔧 Bypass cluster-mode if running on 1 worker

### PR DESCRIPTION
**Pull request by ThePooN**

### CODE REVIEW

**Comment by peppy** [comment]
What's the use case for this? Local testing?

**Comment by ThePooN** [comment]
Reducing resources overhead and complexity if running on 1 worker. Moreover, if we're switching to 1 worker in production, it will actually make crashes (if any) be handled by Kubernetes and bring some kind of visibility rather than none at all.

**Review by peppy — APPROVED** [review]

**Comment by nanaya** [comment]
am I doing something wrong here...

```
$ WORKERS=1 node scthumbd.js
file:///home/edho/osu/scthumber/scthumbd.js:84
  console.log(`${'[w]'.magenta} Worker ${'%s'.green} started...`, cluster.worker.id);
                                                                                 ^

TypeError: Cannot read properties of undefined (reading 'id')
    at file:///home/edho/osu/scthumber/scthumbd.js:84:82
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.17.1
```

also the [docs](https://nodejs.org/api/cluster.html#clusterworker) say

> A reference to the current worker object. Not available in the primary process.

**Comment by peppy** [comment]
Full disclosure that i assumed this was tested and didn't test myself 😅

**Comment by ThePooN** [comment]
That was my first attempt. It's obviously flawed (even if it worked, the console.log calls wouldn't make sense).  
I committed before `git add`-ing the required changes and didn't realize when opening the PR, my bad...

Hotfix: https://github.com/ppy/scthumber/pull/18

**Pull request merged**
